theme: jekyll-theme-cayman
exclude:
  - book/

# Meta =======================================================================
title: Ajaxinate - Shopify endless scroll pagination plugin
description: Shopify ajax pagination plugin

# Site =======================================================================
name: Ajaxinate
subtitle: Endless scrolling made easy
github_url: https://github.com/Elkfox/Ajaxinate
download_url: https://github.com/Elkfox/Ajaxinate/archive/master.zip
demo_url: https://ajaxify.myshopify.com/collections/all
